name: Build and Deploy Angular to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.AZURE_PASSWORD }}" | docker login <registry-name>.azurecr.io -u ${{ secrets.AZURE_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t <registry-name>.azurecr.io/your-angular-app:latest .
        docker push <registry-name>.azurecr.io/your-angular-app:latest

    - name: Deploy to Azure Web App
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        az webapp config container set --name <web-app-name> --resource-group <resource-group-name> --docker-custom-image-name <registry-name>.azurecr.io/your-angular-app:latest --docker-registry-server-url https://<registry-name>.azurecr.io

